export const states = [
    {
        id: '1',
        name: 'Oregon',
        nickname: 'The Beaver State',
        img: 'assets/icons8-oregon-100.png',
        animal: 'American beaver',
        animalImg: '../assets/francesco-ungaro-cHVKmOwd0A8-unsplash.jpg',
        flower: 'Oregon Grape',
        flowerImg: '../assets/oregon-state-flower-gcdc3b0078_1920.jpg',
        Fruit: 'Pear',
        fruitImg: '../assets/pexels-mali-maeder-568471.jpg',
        Tree: 'Douglas-fir',
        treeImg: '../assets/douglas-fir-g2ee540245_1920.jpg',
    },
    {
        id: '2',
        name: 'Maine',
        nickname: 'The Pine Tree State',
        img: 'assets/icons8-maine-100.png',
        animal: 'Moose',
        animalImg: '../assets/shivam-kumar-MVIqwQvkwG4-unsplash.jpg',
        flower: 'White Pine Cone',
        flowerImg: 'https://upload.wikimedia.org/wikipedia/commons/0/02/Pinus_strobus_cone_sciondriver.jpg',
        Fruit: 'Wild blueberry',
        fruitImg: '../assets/pexels-lumn-308188.jpg',
        Tree: 'White Pine',
        treeImg: '../assets/pine-g73b9f6645_1920.jpg',
    },
    {
        id: '3',
        name: 'Washington',
        nickname: 'The Evergreen State',
        img: 'assets/icons8-washington-100.png',
        animal: 'Olympic Marmot',
        animalImg: '../assets/marmot-g70ce7cf0f_640.jpg',
        flower: 'Pacific rhododendron',
        flowerImg: '../assets/plant-ge3bcee006_1920.jpg',
        Fruit: 'Apple',
        fruitImg: '../assets/apple-g8c9a0d6c0_1920.jpg',
        Tree: 'Western hemlock',
        treeImg: '../assets/hemlock-g32aff4282_1920.jpg',
    },
    {
        id: '4',
        name: 'Colorado',
        nickname: 'The Centennial State',
        img: 'assets/icons8-colorado-100.png',
        animal: 'Rocky Mountain Bighorn Sheep',
        animalImg: '../assets/bighorn-sheep-ge666925aa_1920.jpg',
        flower: 'Rocky Mountain Columbine',
        flowerImg: '../assets/rocky-mountain-columbine-g6d4b4b402_1920.jpg',
        Fruit: 'None. So here is a cool photo of Colorado!',
        fruitImg: '../assets/holly-mandarich-4VgatlFyUpQ-unsplash.jpg',
        Tree: 'Colorado Blue Spruce',
        treeImg: '../assets/spruce-g984d1aa42_1920.jpg',
    }
];