export const states = [
    {
        id: '1',
        name: 'Oregon',
        img: 'assets/icons8-oregon-100.png',
        animal: 'American beaver',
        animalImg: 'assets/francesco-ungaro-cHVKmOwd0A8-unsplash.jpg',
        flower: 'Oregon-grape',
        flowerImg: 'assets/oregon-state-flower-gcdc3b0078_1920.jpg',
        Fruit: 'Pear',
        Tree: 'Douglas-fir',
    },
    {
        id: '2',
        name: 'Maine',
        img: 'assets/icons8-maine-100.png',
        animal: 'Moose',
        animalImg: 'assets/shivam-kumar-MVIqwQvkwG4-unsplash.jpg',
        flower: 'White Pine Cone',
        flowerImg: 'https://upload.wikimedia.org/wikipedia/commons/0/02/Pinus_strobus_cone_sciondriver.jpg',
        Fruit: 'Wild blueberry',
        Tree: 'White Pine',
    },
    {
        id: '3',
        name: 'Washington',
        img: 'assets/icons8-washington-100.png',
        animal: 'Olympic Marmot',
        animalImg: 'assets/marmot-g70ce7cf0f_640.jpg',
        flower: 'Pacific rhododendron',
        flowerImg: 'assets/plant-ge3bcee006_1920.jpg',
        Fruit: 'Apple',
        Tree: 'Western hemlock',
    },
    {
        id: '4',
        name: 'Colorado',
        img: 'assets/icons8-colorado-100.png',
        animal: 'Rocky Mountain Bighorn Sheep',
        animalImg: 'assets/bighorn-sheep-ge666925aa_1920.jpg',
        flower: 'Rocky Mountain Columbine',
        flowerImg: 'assets/rocky-mountain-columbine-g6d4b4b402_1920.jpg',
        Fruit: 'None',
        Tree: 'Colorado Blue Spruce',
    }
];